import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Tokenomics</h1>
        <div className={styles.imageContainer}>
          <li>
            <img src='http://lorempixel.com/100/100/city' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/nature' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/abstract' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/cats' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/food' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/animals' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/business' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/people' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/people' alt='...' />
          </li>
          <li>
            <img src='http://lorempixel.com/100/100/people' alt='...' />
          </li>
        </div>
      </main>
    </div>
  );
};

export default Home;
